import React from 'react';
export const complianceDetails = () => <div>compliance distinct</div>;
export const compliance_detail_0 = (p:any)=> <div>compliance 0 explainable</div>;
export const compliance_detail_1 = (p:any)=> <div>compliance 1 audit</div>;
export const compliance_detail_2 = (p:any)=> <div>compliance 2 model cards</div>;
export const compliance_detail_3 = (p:any)=> <div>compliance 3 regulator</div>;
export const compliance_detail_4 = (p:any)=> <div>compliance 4 explainable</div>;
export const compliance_detail_5 = (p:any)=> <div>compliance 5 audit</div>;
export const compliance_detail_6 = (p:any)=> <div>compliance 6 model cards</div>;
export const compliance_detail_7 = (p:any)=> <div>compliance 7 regulator</div>;
export const compliance_detail_8 = (p:any)=> <div>compliance 8 explainable</div>;
export const compliance_detail_9 = (p:any)=> <div>compliance 9 audit</div>;
export const compliance_detail_10 = (p:any)=> <div>compliance 10 model cards</div>;
export const compliance_detail_11 = (p:any)=> <div>compliance 11 regulator</div>;
export const compliance_detail_12 = (p:any)=> <div>compliance 12 explainable</div>;
export const compliance_detail_13 = (p:any)=> <div>compliance 13 audit</div>;
export const compliance_detail_14 = (p:any)=> <div>compliance 14 model cards</div>;
export const compliance_detail_15 = (p:any)=> <div>compliance 15 regulator</div>;
export const compliance_detail_16 = (p:any)=> <div>compliance 16 explainable</div>;
export const compliance_detail_17 = (p:any)=> <div>compliance 17 audit</div>;
export const compliance_detail_18 = (p:any)=> <div>compliance 18 model cards</div>;
export const compliance_detail_19 = (p:any)=> <div>compliance 19 regulator</div>;