import React from 'react';
export const anomaliesDetails = () => <div>anomalies distinct</div>;
export const anomalies_detail_0 = (p:any)=> <div>anomalies 0 staged accident</div>;
export const anomalies_detail_1 = (p:any)=> <div>anomalies 1 outlier</div>;
export const anomalies_detail_2 = (p:any)=> <div>anomalies 2 anomaly</div>;
export const anomalies_detail_3 = (p:any)=> <div>anomalies 3 repeat</div>;
export const anomalies_detail_4 = (p:any)=> <div>anomalies 4 staged accident</div>;
export const anomalies_detail_5 = (p:any)=> <div>anomalies 5 outlier</div>;
export const anomalies_detail_6 = (p:any)=> <div>anomalies 6 anomaly</div>;
export const anomalies_detail_7 = (p:any)=> <div>anomalies 7 repeat</div>;
export const anomalies_detail_8 = (p:any)=> <div>anomalies 8 staged accident</div>;
export const anomalies_detail_9 = (p:any)=> <div>anomalies 9 outlier</div>;
export const anomalies_detail_10 = (p:any)=> <div>anomalies 10 anomaly</div>;
export const anomalies_detail_11 = (p:any)=> <div>anomalies 11 repeat</div>;
export const anomalies_detail_12 = (p:any)=> <div>anomalies 12 staged accident</div>;
export const anomalies_detail_13 = (p:any)=> <div>anomalies 13 outlier</div>;
export const anomalies_detail_14 = (p:any)=> <div>anomalies 14 anomaly</div>;
export const anomalies_detail_15 = (p:any)=> <div>anomalies 15 repeat</div>;
export const anomalies_detail_16 = (p:any)=> <div>anomalies 16 staged accident</div>;
export const anomalies_detail_17 = (p:any)=> <div>anomalies 17 outlier</div>;
export const anomalies_detail_18 = (p:any)=> <div>anomalies 18 anomaly</div>;
export const anomalies_detail_19 = (p:any)=> <div>anomalies 19 repeat</div>;