import React from 'react';
export const investigationDetails = () => <div>investigation distinct</div>;
export const investigation_detail_0 = (p:any)=> <div>investigation 0 case file</div>;
export const investigation_detail_1 = (p:any)=> <div>investigation 1 evidence</div>;
export const investigation_detail_2 = (p:any)=> <div>investigation 2 timeline</div>;
export const investigation_detail_3 = (p:any)=> <div>investigation 3 chain</div>;
export const investigation_detail_4 = (p:any)=> <div>investigation 4 case file</div>;
export const investigation_detail_5 = (p:any)=> <div>investigation 5 evidence</div>;
export const investigation_detail_6 = (p:any)=> <div>investigation 6 timeline</div>;
export const investigation_detail_7 = (p:any)=> <div>investigation 7 chain</div>;
export const investigation_detail_8 = (p:any)=> <div>investigation 8 case file</div>;
export const investigation_detail_9 = (p:any)=> <div>investigation 9 evidence</div>;
export const investigation_detail_10 = (p:any)=> <div>investigation 10 timeline</div>;
export const investigation_detail_11 = (p:any)=> <div>investigation 11 chain</div>;
export const investigation_detail_12 = (p:any)=> <div>investigation 12 case file</div>;
export const investigation_detail_13 = (p:any)=> <div>investigation 13 evidence</div>;
export const investigation_detail_14 = (p:any)=> <div>investigation 14 timeline</div>;
export const investigation_detail_15 = (p:any)=> <div>investigation 15 chain</div>;
export const investigation_detail_16 = (p:any)=> <div>investigation 16 case file</div>;
export const investigation_detail_17 = (p:any)=> <div>investigation 17 evidence</div>;
export const investigation_detail_18 = (p:any)=> <div>investigation 18 timeline</div>;
export const investigation_detail_19 = (p:any)=> <div>investigation 19 chain</div>;