import React from 'react';
export const rulesDetails = () => <div>rules distinct</div>;
export const rules_detail_0 = (p:any)=> <div>rules 0 explainable</div>;
export const rules_detail_1 = (p:any)=> <div>rules 1 regulator</div>;
export const rules_detail_2 = (p:any)=> <div>rules 2 audit trail</div>;
export const rules_detail_3 = (p:any)=> <div>rules 3 Drools</div>;
export const rules_detail_4 = (p:any)=> <div>rules 4 explainable</div>;
export const rules_detail_5 = (p:any)=> <div>rules 5 regulator</div>;
export const rules_detail_6 = (p:any)=> <div>rules 6 audit trail</div>;
export const rules_detail_7 = (p:any)=> <div>rules 7 Drools</div>;
export const rules_detail_8 = (p:any)=> <div>rules 8 explainable</div>;
export const rules_detail_9 = (p:any)=> <div>rules 9 regulator</div>;
export const rules_detail_10 = (p:any)=> <div>rules 10 audit trail</div>;
export const rules_detail_11 = (p:any)=> <div>rules 11 Drools</div>;
export const rules_detail_12 = (p:any)=> <div>rules 12 explainable</div>;
export const rules_detail_13 = (p:any)=> <div>rules 13 regulator</div>;
export const rules_detail_14 = (p:any)=> <div>rules 14 audit trail</div>;
export const rules_detail_15 = (p:any)=> <div>rules 15 Drools</div>;
export const rules_detail_16 = (p:any)=> <div>rules 16 explainable</div>;
export const rules_detail_17 = (p:any)=> <div>rules 17 regulator</div>;
export const rules_detail_18 = (p:any)=> <div>rules 18 audit trail</div>;
export const rules_detail_19 = (p:any)=> <div>rules 19 Drools</div>;