import React from 'react';
export const claimsDetails = () => <div>claims distinct</div>;
export const claims_detail_0 = (p:any)=> <div>claims 0 FNOL</div>;
export const claims_detail_1 = (p:any)=> <div>claims 1 ingestion</div>;
export const claims_detail_2 = (p:any)=> <div>claims 2 validation</div>;
export const claims_detail_3 = (p:any)=> <div>claims 3 staged accident</div>;
export const claims_detail_4 = (p:any)=> <div>claims 4 FNOL</div>;
export const claims_detail_5 = (p:any)=> <div>claims 5 ingestion</div>;
export const claims_detail_6 = (p:any)=> <div>claims 6 validation</div>;
export const claims_detail_7 = (p:any)=> <div>claims 7 staged accident</div>;
export const claims_detail_8 = (p:any)=> <div>claims 8 FNOL</div>;
export const claims_detail_9 = (p:any)=> <div>claims 9 ingestion</div>;
export const claims_detail_10 = (p:any)=> <div>claims 10 validation</div>;
export const claims_detail_11 = (p:any)=> <div>claims 11 staged accident</div>;
export const claims_detail_12 = (p:any)=> <div>claims 12 FNOL</div>;
export const claims_detail_13 = (p:any)=> <div>claims 13 ingestion</div>;
export const claims_detail_14 = (p:any)=> <div>claims 14 validation</div>;
export const claims_detail_15 = (p:any)=> <div>claims 15 staged accident</div>;
export const claims_detail_16 = (p:any)=> <div>claims 16 FNOL</div>;
export const claims_detail_17 = (p:any)=> <div>claims 17 ingestion</div>;
export const claims_detail_18 = (p:any)=> <div>claims 18 validation</div>;
export const claims_detail_19 = (p:any)=> <div>claims 19 staged accident</div>;