import React from 'react';
export const entitiesDetails = () => <div>entities distinct</div>;
export const entities_detail_0 = (p:any)=> <div>entities 0 entity resolution</div>;
export const entities_detail_1 = (p:any)=> <div>entities 1 shell identities</div>;
export const entities_detail_2 = (p:any)=> <div>entities 2 repeat claimant</div>;
export const entities_detail_3 = (p:any)=> <div>entities 3 fuzzy match</div>;
export const entities_detail_4 = (p:any)=> <div>entities 4 entity resolution</div>;
export const entities_detail_5 = (p:any)=> <div>entities 5 shell identities</div>;
export const entities_detail_6 = (p:any)=> <div>entities 6 repeat claimant</div>;
export const entities_detail_7 = (p:any)=> <div>entities 7 fuzzy match</div>;
export const entities_detail_8 = (p:any)=> <div>entities 8 entity resolution</div>;
export const entities_detail_9 = (p:any)=> <div>entities 9 shell identities</div>;
export const entities_detail_10 = (p:any)=> <div>entities 10 repeat claimant</div>;
export const entities_detail_11 = (p:any)=> <div>entities 11 fuzzy match</div>;
export const entities_detail_12 = (p:any)=> <div>entities 12 entity resolution</div>;
export const entities_detail_13 = (p:any)=> <div>entities 13 shell identities</div>;
export const entities_detail_14 = (p:any)=> <div>entities 14 repeat claimant</div>;
export const entities_detail_15 = (p:any)=> <div>entities 15 fuzzy match</div>;
export const entities_detail_16 = (p:any)=> <div>entities 16 entity resolution</div>;
export const entities_detail_17 = (p:any)=> <div>entities 17 shell identities</div>;
export const entities_detail_18 = (p:any)=> <div>entities 18 repeat claimant</div>;
export const entities_detail_19 = (p:any)=> <div>entities 19 fuzzy match</div>;