import React from 'react';
export const reportingDetails = () => <div>reporting distinct</div>;
export const reporting_detail_0 = (p:any)=> <div>reporting 0 case file PDF</div>;
export const reporting_detail_1 = (p:any)=> <div>reporting 1 evidence packet</div>;
export const reporting_detail_2 = (p:any)=> <div>reporting 2 regulator</div>;
export const reporting_detail_3 = (p:any)=> <div>reporting 3 case file PDF</div>;
export const reporting_detail_4 = (p:any)=> <div>reporting 4 evidence packet</div>;
export const reporting_detail_5 = (p:any)=> <div>reporting 5 regulator</div>;
export const reporting_detail_6 = (p:any)=> <div>reporting 6 case file PDF</div>;
export const reporting_detail_7 = (p:any)=> <div>reporting 7 evidence packet</div>;
export const reporting_detail_8 = (p:any)=> <div>reporting 8 regulator</div>;
export const reporting_detail_9 = (p:any)=> <div>reporting 9 case file PDF</div>;
export const reporting_detail_10 = (p:any)=> <div>reporting 10 evidence packet</div>;
export const reporting_detail_11 = (p:any)=> <div>reporting 11 regulator</div>;
export const reporting_detail_12 = (p:any)=> <div>reporting 12 case file PDF</div>;
export const reporting_detail_13 = (p:any)=> <div>reporting 13 evidence packet</div>;
export const reporting_detail_14 = (p:any)=> <div>reporting 14 regulator</div>;
export const reporting_detail_15 = (p:any)=> <div>reporting 15 case file PDF</div>;
export const reporting_detail_16 = (p:any)=> <div>reporting 16 evidence packet</div>;
export const reporting_detail_17 = (p:any)=> <div>reporting 17 regulator</div>;
export const reporting_detail_18 = (p:any)=> <div>reporting 18 case file PDF</div>;
export const reporting_detail_19 = (p:any)=> <div>reporting 19 evidence packet</div>;