import React from 'react';
export const scoringDetails = () => <div>scoring distinct</div>;
export const scoring_detail_0 = (p:any)=> <div>scoring 0 fraud score</div>;
export const scoring_detail_1 = (p:any)=> <div>scoring 1 risk</div>;
export const scoring_detail_2 = (p:any)=> <div>scoring 2 SHAP</div>;
export const scoring_detail_3 = (p:any)=> <div>scoring 3 explainability</div>;
export const scoring_detail_4 = (p:any)=> <div>scoring 4 fraud score</div>;
export const scoring_detail_5 = (p:any)=> <div>scoring 5 risk</div>;
export const scoring_detail_6 = (p:any)=> <div>scoring 6 SHAP</div>;
export const scoring_detail_7 = (p:any)=> <div>scoring 7 explainability</div>;
export const scoring_detail_8 = (p:any)=> <div>scoring 8 fraud score</div>;
export const scoring_detail_9 = (p:any)=> <div>scoring 9 risk</div>;
export const scoring_detail_10 = (p:any)=> <div>scoring 10 SHAP</div>;
export const scoring_detail_11 = (p:any)=> <div>scoring 11 explainability</div>;
export const scoring_detail_12 = (p:any)=> <div>scoring 12 fraud score</div>;
export const scoring_detail_13 = (p:any)=> <div>scoring 13 risk</div>;
export const scoring_detail_14 = (p:any)=> <div>scoring 14 SHAP</div>;
export const scoring_detail_15 = (p:any)=> <div>scoring 15 explainability</div>;
export const scoring_detail_16 = (p:any)=> <div>scoring 16 fraud score</div>;
export const scoring_detail_17 = (p:any)=> <div>scoring 17 risk</div>;
export const scoring_detail_18 = (p:any)=> <div>scoring 18 SHAP</div>;
export const scoring_detail_19 = (p:any)=> <div>scoring 19 explainability</div>;